### GET All
GET http://localhost:8080/api/v1/dishes
Authorization: Basic admin admin
Accept: application/json

### GET All bad creds
GET http://localhost:8080/api/v1/dishes
Authorization: Basic test test
Accept: application/json

### GET 1
GET http://localhost:8080/api/v1/dishes/1
Authorization: Basic admin admin
Accept: application/json

### DELETE 4
DELETE http://localhost:8080/api/v1/dishes/4
Authorization: Basic admin admin
Accept: application/json

### Create
POST http://localhost:8080/api/v1/dishes
Authorization: Basic admin admin
Accept: application/json
Content-Type: application/json

{
  "name": "newFood",
  "description": "description-food",
  "calories": 555,
  "price": 10.5,
  "category": "someCategory",
  "cuisine": "Italy",
  "preparationTime": 10
}

### Update
PUT http://localhost:8080/api/v1/dishes
Authorization: Basic admin admin
Accept: application/json
Content-Type: application/json

{
  "id": "5",
  "name": "nameUpdated",
  "description": "description-new",
  "calories": 0,
  "price": 999,
  "category": "newCategory",
  "cuisine": "Ukraine",
  "preparationTime": 99
}


### get fast food
GET http://localhost:8080/api/v1/dishes/category/Fast Food
Authorization: Basic admin admin
Accept: application/json

### get most expensive dish
GET http://localhost:8080/api/v1/dishes/most-expensive
Authorization: Basic admin admin
Accept: application/json

### lower calories than 500
GET http://localhost:8080/api/v1/dishes/low-calorie/500
Authorization: Basic admin admin
Accept: application/json

### lower calories than 600
GET http://localhost:8080/api/v1/dishes/low-calorie/600
Authorization: Basic admin admin
Accept: application/json